import iPhone13 from './Images/iphone13.jfif';
import blast from './Images/blast.jfif';
import iphone from './Images/iphone.jpg';
import ponny from './Images/ponny.jpg';
import xiuwoo from './Images/xiuwoo.jpg';
import mysteryBox from './Images/mysteryBox.jpg';
import slime from './Images/slime.jpg';
import orbz from './Images/orbz.webp';
import twister from './Images/twister.webp';
import akfosh from './Images/akfosh.webp';
import home from './Images/home.webp';
import doable from './Images/doable.jpg';
import crown from './Images/crown.jpg';

const Products = [
    {
        id: 1,
        code: 'GET 100 AED OFF | USE CODE:',
        poster: iPhone13,
        title: 'iPhone 13 Pro Max 256GB Sierra Blue 5G With Facetime',
        price: 'AED 4649.00',
        discount: 'AED 5119',
        off: '9% Off',
        arrive: 'Arrives',
        date: 'Tomorrow, Mar 15',
        express: 'express',
    },
    {
        id: 2,
        code: 'GET 100 AED OFF | USE CODE:',
        poster: iphone,
        title: 'iPhone 13 128GB Blue 5G With FaceTime',
        price: 'AED 2894.95',
        discount: 'AED 3399.00',
        off: '14% Off',
        arrive: 'Arrives',
        date: 'Tomorrow, Mar 15',
        express: 'express',
    },
    {
        id: 3,
        code: 'GET 100 AED OFF | USE CODE:',
        poster: ponny,
        title: 'Magical Potion Surprise Blind Bag Batch',
        price: 'AED 9.36',
        discount: 'AED 30.00',
        off: '68% Off',
        arrive: 'Arrives',
        date: 'Tomorrow, Mar 15',
        express: 'express',
    },
    {
        id: 4,
        code: 'GET 100 AED OFF | USE CODE:',
        poster: xiuwoo,
        title: '3300-Piece Small Colourful Bracelet Beads With A-Z',
        price: 'AED 15.60',
        discount: 'AED 44.00',
        off: '64% Off',
        arrive: 'Arrives',
        date: 'Tomorrow, Mar 15',
        express: 'express',
    },
    {
        id: 5,
        code: 'GET 100 AED OFF | USE CODE:',
        poster: mysteryBox,
        title: 'Pack Of 20 Mystery Each Box 22cm',
        price: 'AED 21.00',
        discount: 'AED 44.00',
        off: '64% Off',
        arrive: 'Arrives',
        date: 'Tomorrow, Mar 15',
        express: 'express',
    },
    {
        id: 6,
        code: 'GET 100 AED OFF | USE CODE:',
        poster: slime,
        title: 'Slime Glam Mini Shaker Surprise 11.5 x 6 x 14cm',
        price: 'AED 15.40',
        discount: 'AED 30.00',
        off: '48% Off',
        arrive: 'Arrives',
        date: 'Tomorrow, Mar 15',
        express: 'express',
    },
    {
        id: 7,
        code: 'GET 100 AED OFF | USE CODE:',
        poster: orbz,
        title: 'My Little Pony Orbz Balloon XL',
        price: 'AED 24.70',
        discount: 'AED 65.00',
        off: '62% Off',
        arrive: 'Arrives',
        date: 'Tomorrow, Mar 15',
        express: 'express',
    },
    {
        id: 8,
        code: 'GET 100 AED OFF | USE CODE:',
        poster: blast,
        title: 'Funny Toy Blast Box Action Balloon Blasting Family Party ',
        price: 'AED 19.00',
        discount: 'AED 29.80',
        off: '36% Off',
        arrive: 'Arrives',
        date: 'Tomorrow, Mar 15',
        express: 'express',
    },
    {
        id: 9,
        code: 'GET 100 AED OFF | USE CODE:',
        poster: twister,
        title: 'Tricky Twister Classic Multi Player Challenging Game',
        price: 'AED 68.25',
        discount: 'AED 160.00',
        off: '57% Off',
        arrive: 'Arrives',
        date: 'Tomorrow, Mar 15',
        express: 'express',
    },
    {
        id: 10,
        code: 'GET 100 AED OFF | USE CODE:',
        poster: akfosh,
        title: 'Cards Party Board Game',
        price: 'AED 14.95',
        discount: 'AED 40.00',
        off: '62% Off',
        arrive: 'Arrives',
        date: 'Tomorrow, Mar 15',
        express: 'express',
    },
    {
        id: 11,
        code: 'GET 100 AED OFF | USE CODE:',
        poster: home,
        title: 'Boasts Unique Figure Educational Development And Learning ',
        price: 'AED 15.60',
        discount: 'AED 19.75',
        off: '21% Off',
        arrive: 'Arrives',
        date: 'Tomorrow, Mar 15',
        express: 'express',
    },
    {
        id: 12,
        code: 'GET 100 AED OFF | USE CODE:',
        poster: doable,
        title: 'Dobble Card Game 9.5x9.5x4.5cm ',
        price: 'AED 15.00',
        discount: 'AED 55.00',
        off: '72% Off',
        arrive: 'Arrives',
        date: 'Tomorrow, Mar 15',
        express: 'express',
    },
    {
        id: 13,
        code: 'GET 100 AED OFF | USE CODE:',
        poster: crown,
        title: 'Musical Spinning Crown Game Party Toy',
        price: 'AED 68.55',
        arrive: 'Arrives',
        date: 'Tomorrow, Mar 15',
        express: 'express',
    }
]

export default Products;